-- 5. Write a function that returns a report of all open rooms (not used) on a particular day (input) and which tavern they belong to
-- CREATE TEMPORARY TABLE counter (c INT);
-- INSERT INTO counter VALUES (0);
-- DELIMITER //
-- CREATE FUNCTION counter () RETURNS INT
--   BEGIN
--     UPDATE counter SET c = c + 1;
--     RETURN (SELECT c FROM counter LIMIT 1);
--   END //
-- DELIMITER ;
--
-- SELECT * FROM counter;
